# Generated by Django 3.2.6 on 2021-08-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='list_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
